# Generated by Django 4.1.3 on 2023-03-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0002_rename_therapists_therapist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
